---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by smarc.
--- DateTime: 26/03/2021 21:20
---
-- modulos do ESP-12:
--        modules: color_utils,file,gpio,net,node,pcm,tmr,uart,websocket,wifi,ws2812,ws2812_effects


ws2812.init(ws2812.MODE_SINGLE)
-- create a buffer, 60 LEDs with 3 color bytes
strip_buffer = ws2812.newBuffer(200, 3)

-- apaga tudo:
function apaga()
strip_buffer:fill(0, 0, 0)
ws2812.write(strip_buffer)
end

apaga()

-- init the effects module, set color to red and start blinking
ws2812_effects.init(strip_buffer)
ws2812_effects.set_speed(100)
ws2812_effects.set_brightness(50)
ws2812_effects.set_color(0,255,0)
ws2812_effects.set_mode("circus_combustus")
ws2812_effects.start()

function startup()
    tmrStartup = nil
    if file.open("ok.flag") == nil then
	    print("ok.flag foi apagado ou renomeado.")
	    print("talvez file.rename('not_ok.flag','ok.flag') para restaurar")
    else
	    print("Running")
	    file.close("ok.flag")
	    -- the actual application is stored in 'application.lua'
	    pcall(node.LFS.get("_init"))
--        LFS.HTTP_OTA('www.cachambi.com.br','/relogioBPICM/','LFS.img')
        LFS.tetris()
    end
  end

  --print("versão: " .. LFS._time)
  print("Se quiser cancelar a inicializacao, digite rapidamente:")
  print("file.rename('ok.flag','not_ok.flag')")
  print("Waiting ...")

if not tmr.create():alarm(3000, tmr.ALARM_SINGLE, function()
    ws2812_effects.stop()
    apaga()
    startup()
end)
then
    print("eita!")
end


--[[
  Executa funcao sem lançar error. Printa o callstack no terminal.
--]]
function chamar(fn, onError)
  local ok, res = xpcall(fn, debug.traceback)
  if not ok then
     return res
  else
     print(res)
     if onError then
        onError()
     end
  end
end