--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by smarc.
--- DateTime: 26/03/2021 21:20
---
-- modulos do ESP-12:
--        modules: color_utils,file,gpio,net,node,pcm,tmr,uart,websocket,wifi,ws2812,ws2812_effects

-- Função para ler e parsear o arquivo de configuração
function load_config()
    if file.exists("config.json") then
        local f = file.open("config.json", "r")
        local content = f:read()
        f:close()

        -- Parse JSON
        local config = sjson.decode(content)
        return config
    else
        print("Erro: Arquivo config.json não encontrado!")
        return nil
    end
end

-- Carrega as configurações
local config = load_config()

-- Wifi setup
wifi.setmode(wifi.STATION, true)

if config then
    local station_cfg = {}
    station_cfg.ssid = config.wifi.ssid
    station_cfg.pwd = config.wifi.password
    station_cfg.save = true
    wifi.sta.config(station_cfg)
else
    print("Falha ao carregar configurações WiFi")
end

function startup()
    tmrStartup = nil
    if file.open("ok.flag") == nil then
	    print("ok.flag foi apagado ou renomeado.")
	    print("talvez file.rename('not_ok.flag','ok.flag') para restaurar")
    else
	    print("Running")
	    file.close("ok.flag")
	    pcall(node.LFS.get("_init"))
--        LFS.HTTP_OTA('www.cachambi.com.br','/relogioBPICM/','LFS.img')
        LFS.tetris()
    end
  end

  --print("versão: " .. LFS._time)
  print("Se quiser cancelar a inicializacao, digite rapidamente:")
  print("file.rename('ok.flag','not_ok.flag')")
  print("Waiting ...")

if not tmr.create():alarm(3000, tmr.ALARM_SINGLE, function()
    startup()
end)
then
    print("eita!")
end


--[[
  Executa funcao sem lançar error. Printa o callstack no terminal.
--]]
function chamar(fn, onError)
  local ok, res = xpcall(fn, debug.traceback)
  if not ok then
     return res
  else
     print(res)
     if onError then
        onError()
     end
  end
end