---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by smarc.
--- DateTime: 26/03/2021 21:20
---
-- modulos do ESP-12:
--        modules: color_utils,file,gpio,net,node,pcm,tmr,uart,websocket,wifi,ws2812,ws2812_effects

ws2812.init(ws2812.MODE_SINGLE)
-- create a buffer, 60 LEDs with 3 color bytes
strip_buffer = ws2812.newBuffer(200, 3)
-- init the effects module, set color to red and start blinking
ws2812_effects.init(strip_buffer)
ws2812_effects.set_speed(100)
ws2812_effects.set_brightness(50)
ws2812_effects.set_color(0,255,0)
ws2812_effects.set_mode("circus_combustus")
ws2812_effects.start()
